### ISSUE TITLE
Question : compatibility

### ISSUE THREAD

**Issue by ghost** [weluse/yii2-mailjet#3]
```
$ composer require weluse/yii2-mailjet
Using version ^0.1.0 for weluse/yii2-mailjet
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: mailjet/mailjet-apiv3-php[v1.1.5, v1.1.7].
    - Can only install one of: mailjet/mailjet-apiv3-php[v1.1.7, v1.1.5].
    - Can only install one of: mailjet/mailjet-apiv3-php[v1.1.5, v1.1.7].
    - weluse/yii2-mailjet v0.1.0 requires mailjet/mailjet-apiv3-php 1.1.5 -> satisfiable by mailjet/mailjet-apiv3-php[v1.1.5].
    - Installation request for weluse/yii2-mailjet ^0.1.0 -> satisfiable by weluse/yii2-mailjet[v0.1.0].
    - Installation request for mailjet/mailjet-apiv3-php (locked at v1.1.7, required as ^1.1) -> satisfiable by mailjet/mailjet-apiv3-php[v1.1.7].


Installation failed, reverting ./composer.json to its original content.
```

Not very experienced all of composer, Yii2, and MailJet so unsure here.
Which is best for me to change? The composer requirement here of the composer file at https://github.com/mailjet/mailjet-apiv3-php/blob/master/composer.json ?

Not even sure what I would change. Thanks in advance for any advice.

Later... this worked, composer update ran ok. But I think I may opened yself up to who-knows-what issues later... ;)

```
        "mailjet/mailjet-apiv3-php": "*",
        "weluse/yii2-mailjet": "*"
```

**Comment by dbanck** [comment]
It seems that you have locked your `mailjet/mailjet-apiv3-php` version at `1.1.7` and we've pinned `mailjet/mailjet-apiv3-php` inside this project to `1.1.5`.

This is somewhat our fault, because we've specified an exact version and did not keep it up to date with the latest versions of `mailjet/mailjet-apiv3-php`. I would suggest we change this to a more relaxed versioning with a caret, like `^1.1.5`. So every version of `mailjet/mailjet-apiv3-php` between `>=1.1.5` and `<2.0.0` should work with this library. Any objections @Julian-B90?

You just have to wait a few hours till a new version of this library is published and your installation should work fine.
